os:
  - linux

language: go

env:
  - GOLANGCI_RELEASE="v1.11.2"

go:
  - "1.13.x"
  # recently this is causing a SIGSEGV in the linter.
  # - master

go_import_path: github.com/corywalker/expreduce

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin ${GOLANGCI_RELEASE}
  #- go get -u github.com/golang/lint/golint
  #- go get golang.org/x/tools/cmd/goimports
  #- go get honnef.co/go/tools/cmd/staticcheck
  #- go get honnef.co/go/tools/cmd/unused
  #- go get -u mvdan.cc/unparam
  #- go get github.com/gordonklaus/ineffassign
script:
  #- 'golint ./... | grep -v "be unexported" | grep -v "resourcesRubi"'
  #- goimports -l . | grep -v resources.go
  #- staticcheck
  #- unused
  #- unparam
  #- ineffassign .
  - golangci-lint run -e "(is unused|is not checked|Sprintf format )"
  - go test -v ./...
  - go test -v -race ./... -run Concurrency

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

notifications:
  email: false
